name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout репозиторій
        uses: actions/checkout@v4

      - name: Встановлення Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.5

      - name: Налаштування AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Ініціалізація Terraform
        run: terraform init

      - name: Перевірка змін (terraform plan)
        id: plan
        run: terraform plan -out=tfplan

      - name: Застосування змін (terraform apply)
        if: success() && steps.plan.outputs.exitcode == '0'
        run: terraform apply -auto-approve tfplan